##Create 2 4*6 and 6*4 matrices of random numbers
#compute dot products between corresponding columns

In [55]:
import numpy as np
from numpy.random import randn

In [56]:
A = randn(4,6)
A

array([[ 0.66752026,  0.53575526, -1.2240298 ,  0.57391152,  0.9127457 ,
        -1.08958752],
       [-0.62734074, -0.02465   ,  0.15452266,  0.58785812, -0.74376161,
         0.48644862],
       [-0.49853569,  0.13180322, -0.12041444, -0.02716857,  0.60298282,
         1.19020741],
       [ 0.31143474,  1.62031693, -0.12338744,  1.00829513, -1.04372955,
         0.11595564]])

In [57]:
B = randn(6,4)
B

array([[ 0.3288836 , -1.0767036 ,  2.00539783, -1.19922218],
       [ 1.43920581, -0.49776812, -0.23543042, -0.26976785],
       [-0.3564191 , -1.32753472,  0.59244951,  0.25117196],
       [ 0.107255  ,  0.06860965, -1.34704736,  0.96626281],
       [ 0.07300441,  0.62858933,  0.39944798,  1.38875875],
       [ 0.5033232 ,  0.60783497,  0.68543127, -0.34932122]])

In [58]:
#now to verify if the answer is correct, do dot product with a diff method
dp = np.dot(A,B)
print(dp)

[[ 1.00664082  0.59036738 -0.66799419  0.95027237]
 [-0.04327961  0.35108843 -1.91625722  0.16297562]
 [ 0.70881519  1.73163631 -0.00886935  0.92743504]
 [ 2.56868396 -1.49448048 -1.52567951 -1.35729655]]


In [61]:
dp = np.matmul(A,B)
dp

array([[ 1.00664082,  0.59036738, -0.66799419,  0.95027237],
       [-0.04327961,  0.35108843, -1.91625722,  0.16297562],
       [ 0.70881519,  1.73163631, -0.00886935,  0.92743504],
       [ 2.56868396, -1.49448048, -1.52567951, -1.35729655]])