*Test whether dot product of vectors is commutative

In [ ]:
#check if aT*b == bT*a

#generate two 100-element random row vectors, compute dot product awith b and bwith a
#generate two 2 -element row vectors, repeat the same

In [1]:
import numpy as np
from numpy.random import randn

In [4]:
a = randn(100)
b = randn(100)

In [5]:
aT = np.transpose(a) 
bT = np.transpose(b)

In [7]:
aT*b == bT*a

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [8]:
c = np.array([2,5])
d = np.array([-2,0])

In [9]:
c*(np.transpose(d))

array([-4,  0])

In [10]:
d*(np.transpose(c))

array([-4,  0])

Hence from the above results it is established that vector dot product is commutative 