i -> sqrt(-1)
Let x be sqrt(-1)
=> x**2 = -1
=> x**2+1 = 0

A complex vector can be conceptualized as a 2D vector, where second element is imaginary number.

Let z and w be 2 comnplex numbers
z = a+bi
w = c+di

multiplying them,
z*w = (a+bi)(c+di) = ac + adi +cbi - bd

In [3]:
import numpy as np
import matplotlib.pyplot as plt

In [17]:
#Let us multiply 2 complex vectors

a = np.ndarray(10, dtype=np.complex64)
b = np.ndarray(10, dtype=np.complex64)

In [16]:
a

array([5.3265527e-39+7.8061461e-39j, 7.6224751e-39+8.4489778e-39j,
       1.0102060e-38+8.9081833e-39j, 8.4490030e-39+9.6428882e-39j,
       9.0918500e-39+8.9081931e-39j, 8.9081959e-39+1.0285738e-38j,
       9.0000258e-39+8.7245011e-39j, 1.0469409e-38+9.6428630e-39j,
       8.9081945e-39+1.0193910e-38j, 1.6955711e-43+0.0000000e+00j],
      dtype=complex64)

In [18]:
b

array([5.7857652e-39+8.4489539e-39j, 5.3265527e-39+7.8061461e-39j,
       9.2755463e-39+1.0561242e-38j, 7.6224751e-39+8.4489778e-39j,
       1.0101996e-38+9.0918500e-39j, 1.0102060e-38+8.9081833e-39j,
       8.4489371e-39+9.6428784e-39j, 8.4490030e-39+9.6428896e-39j,
       9.2755379e-39+1.0653065e-38j, 1.0285640e-38+1.6955711e-43j],
      dtype=complex64)

In [19]:
np.transpose(a)*b

array([0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
       0.+0.j, 0.+0.j], dtype=complex64)

In [20]:
np.dot(a,b)

0j

In [21]:
c = np.array([1+3j, -2j , 4, 5])
d = np.array([6+2j, 8,3j,-5])

In [22]:
np.dot(c,d)

(-25+16j)

In [24]:
np.multiply(c,d)

array([  0.+20.j,   0.-16.j,   0.+12.j, -25. +0.j])

In [25]:
np.outer(c,d)

array([[  0.+20.j,   8.+24.j,  -9. +3.j,  -5.-15.j],
       [  4.-12.j,   0.-16.j,   6. -0.j,   0.+10.j],
       [ 24. +8.j,  32. +0.j,   0.+12.j, -20. +0.j],
       [ 30.+10.j,  40. +0.j,   0.+15.j, -25. +0.j]])