In [2]:
import numpy as np

In [3]:
# define matrix and scalar
M = np.array([ [1, 2], [2, 5] ])
s = 2

# pre- and post-multiplication is the same:
print( M*s )
print( s*M )

[[ 2  4]
 [ 4 10]]
[[ 2  4]
 [ 4 10]]


Code challenge:
    
    Test whether some random MXN matrices whether s(A+B) = sA + sB

In [4]:
from numpy.random import randint

In [5]:
m = 7
n = 5

In [7]:
A = randint(0,100,35).reshape(m,n)
B = randint(0,100,35).reshape(m,n)
print(A,B,sep='\n\n')

[[26 16 69  6 98]
 [39 48 83 64  6]
 [13 41 89 26 30]
 [27 46 31 48 96]
 [65 94 93  0  4]
 [33 35 70 66  4]
 [ 5 71 23 35 59]]

[[22 74 55 76 25]
 [32 79 23 35 80]
 [75 62 25 93 91]
 [96 57 17 63 68]
 [27 39  8 15 39]
 [41 27 42 61 15]
 [ 7 85 13 51 31]]


In [8]:
s = randint(1,10,1)
s

array([3])

In [10]:
s*(A+B)

array([[144, 270, 372, 246, 369],
       [213, 381, 318, 297, 258],
       [264, 309, 342, 357, 363],
       [369, 309, 144, 333, 492],
       [276, 399, 303,  45, 129],
       [222, 186, 336, 381,  57],
       [ 36, 468, 108, 258, 270]])

In [11]:
s*A+s*B

array([[144, 270, 372, 246, 369],
       [213, 381, 318, 297, 258],
       [264, 309, 342, 357, 363],
       [369, 309, 144, 333, 492],
       [276, 399, 303,  45, 129],
       [222, 186, 336, 381,  57],
       [ 36, 468, 108, 258, 270]])

In [12]:
s*(A+B) == s*A+s*B

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

Hence from the above, s(A+B) = sA + sB