In [1]:
import numpy as np

In [3]:
M = np.round( 5*np.random.randn(4,4) )

# extract the diagonals
d = np.diag(M)

# notice the two ways of using the diag function
d = np.diag(M) # input is matrix, output is vector
D = np.diag(d) # input is vector, output is matrix
print(d)
print()
print(D)



[-0.  2.  1. -5.]

[[-0.  0.  0.  0.]
 [ 0.  2.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0. -5.]]


In [4]:
# trace as sum of diagonal elements
tr = np.trace(M)
tr2 = sum( np.diag(M) )
print(tr)
print()
print(tr2)

-2.0

-2.0


trace will add the diagonal elements