In [17]:
import numpy as np
import matplotlib.pyplot as plt
import math

Matrix multiplication is not commutative AB!=BA
A(MXN) and B(NXK), matrix multiplication is valid only if inner dimensions match. resultant matrix will have MXK dimensions

###### 4 ways to think about matrix multiplication:

    1. Ordered collection of dot products of rows between left and columns of right matrix
    
          0  1  X  a  b    =  0a+1c  0b+1d
          2  3     c  d       2a+3c  2b+3d
          
    2. Build product matrix one layer at a time. Each layer has rank 1 of infomation at a time. 
    
          0  1  X  a  b    =  0a  0b  +  1c  1d  =  0a+1c  0b+1d
          2  3     c  d       2a  2b     3c  3d     2a+3c  2b+3d
          
    3. Column perspective
          0  1  X  a  b    =  a* 0 + c* 1    b* 0 + d* 1  =   0a+1c  0b+1d
          2  3     c  d          2      3       2      3      2a+3c  2b+3d
          
    4. row perspective
         0  1  X  a  b   = 0[a b] + 1[c d]  =  0a+1c  0b+1d
         2  3     c  d     2[a b]   3[c d]     2a+3c  2b+3d
         

In [20]:
#implement matrix multiplication via layers method

A = np.random.randint(1,5,6).reshape(3,2)
B = np.random.randint(1,5,6).reshape(2,3)

np.matmul(A,B)

array([[ 6, 11,  8],
       [12, 22, 16],
       [ 9, 10, 10]])

In [22]:
np.outer(A,B)

array([[ 2,  8,  4,  8,  6,  8],
       [ 1,  4,  2,  4,  3,  4],
       [ 4, 16,  8, 16, 12, 16],
       [ 2,  8,  4,  8,  6,  8],
       [ 1,  4,  2,  4,  3,  4],
       [ 2,  8,  4,  8,  6,  8]])

In [23]:
## rules for multiplication validity

m = 4
n = 3
k = 6

# make some matrices
A = np.random.randn(m,n)
B = np.random.randn(n,k)
C = np.random.randn(m,k)

# test which multiplications are valid.
# Think of your answer first, then test.
np.matmul(A,B)


array([[-1.22821202, -0.19578241, -4.12270654,  0.55383891,  0.81977427,
        -1.86632717],
       [-1.45092976, -1.8391633 , -2.2242761 ,  0.1030103 ,  0.91694529,
        -1.28115482],
       [ 0.03855548, -1.76813419,  0.67809676, -0.37297453,  0.33117891,
         0.19903598],
       [-0.27129437, -0.25767705,  0.16373087, -0.02807959,  0.04832392,
        -0.0216906 ]])

In [24]:
np.matmul(A,A)


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 3)

In [25]:
np.matmul(np.matrix.transpose(A),C)


array([[-0.9915744 ,  4.2656038 , -0.40370788, -2.32206411,  1.439156  ,
         3.41581789],
       [-0.60394195, -2.35300704,  0.64264582,  0.33636668,  1.42489761,
        -0.64109317],
       [ 0.22586706,  4.5135904 , -1.59054356, -1.15329458, -0.51275537,
         2.08362188]])

In [26]:
np.matmul(B,np.matrix.transpose(B))


array([[ 3.88473224,  1.66300882, -4.47765409],
       [ 1.66300882,  2.54823962, -0.73698784],
       [-4.47765409, -0.73698784,  7.58739619]])

In [27]:
np.matmul(np.matrix.transpose(B),B)


array([[ 1.33552445, -0.93028251,  0.44441402, -0.36323399,  0.10487809,
         0.49224316],
       [-0.93028251,  2.66993648,  2.73360498,  0.26725659, -1.1198525 ,
         0.85655371],
       [ 0.44441402,  2.73360498,  7.9039575 , -0.43792253, -2.0947383 ,
         3.14598919],
       [-0.36323399,  0.26725659, -0.43792253,  0.13496771,  0.02316173,
        -0.25087122],
       [ 0.10487809, -1.1198525 , -2.0947383 ,  0.02316173,  0.64686925,
        -0.78767039],
       [ 0.49224316,  0.85655371,  3.14598919, -0.25087122, -0.78767039,
         1.32911266]])

In [28]:
np.matmul(B,C)


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 6)

In [29]:
np.matmul(C,B)


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 6)

In [30]:
np.matmul(np.matrix.transpose(C),B)


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)

In [31]:
np.matmul(C,np.matrix.transpose(B))

array([[-2.50864186, -1.41720695,  1.07203103],
       [ 1.7116417 ,  0.95774667, -2.59599633],
       [-2.59021659, -2.22692391, -0.23706225],
       [ 1.90667584, -0.73597997, -3.61894692]])