if L,I,V and E were seperate matrices, then (LIVE).T = (E.T).(V.T).(I.T).(L.T)

it means the transpose of product od matrices is equal to the product of transposes of individual matrices multiplied in reverse order

In [10]:
import numpy as np
from numpy.random import randint

In [11]:
n = 2
L = randint(1,10,4).reshape(n,n)
I = randint(1,10,4).reshape(n,n)
V = randint(1,10,4).reshape(n,n)
E = randint(1,10,4).reshape(n,n)

In [12]:
# result of "forward" multiplication and then transpose

res1 = np.matrix.transpose( L @ I @ V @ E )
res1

array([[7996, 4820],
       [9464, 5712]])

In [13]:
# result of "flipped" multiplication of transposed matrices
res2 = np.matrix.transpose(E) @ np.matrix.transpose(V) @ np.matrix.transpose(I) @ np.matrix.transpose(L)
res2

array([[7996, 4820],
       [9464, 5712]])

In [15]:
# test equality by subtracting (ignore possible computer rounding errors)
res1 == res2

array([[ True,  True],
       [ True,  True]])

As indicated from above,(LIVE).T = (E.T).(V.T).(I.T).(L.T)

In [16]:
L @ I

array([[89, 42],
       [53, 26]])

In [17]:
np.matmul(L,I)

array([[89, 42],
       [53, 26]])