Matrix - vector multiplication

A     w   =   v
mXn  nX1      mX1

When a matrix is multiplied by a vector, product will always be a vector

If the vector multiplied is a row vector then product is row vector and if column vector was multiplied then result will always be a column vector.

a  b  X  2  =  a2+b3
c  d     3     c2+d3

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [4]:
A = np.random.randint(1,100,16).reshape(4,4)
A

array([[ 3, 88, 91, 49],
       [62, 73, 40, 11],
       [81, 70, 34, 74],
       [11, 14, 74, 63]])

In [5]:
w = np.array([-1, 0, 1, 2])

In [6]:
A@w  

array([186,   0, 101, 189])

In [7]:
w@A

array([100,  10,  91, 151])

In [8]:
B = np.random.randint(1,100,12).reshape(4,3)
B

array([[87, 82, 65],
       [28, 37, 27],
       [88, 88, 55],
       [42, 57, 88]])

In [9]:
B@w

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 3)

In [10]:
w@B

array([ 85, 120, 166])