In [1]:
import numpy as np
import matplotlib.pyplot as plt
import math

AI = IA = A - multiplicative identity
A+0 = A - Additive Identity

In [2]:
#size of matrices
n = 4

A = np.round( 10*np.random.randn(n,n) )
I = np.eye(n,n)
Z = np.zeros((n,n))

# test both identities
np.array_equal( A@I , A   )

True

In [3]:
np.array_equal( A   , A@I )

True

In [4]:
np.array_equal( A   , A+I )

False

In [5]:
np.array_equal( A   , A+I )

False

In [6]:
np.array_equal( A+Z , A@I )

True

Clearly, to conclude, AI = IA = A and A+Z = A

In [7]:
## the multiplicative method

# specify sizes
m = 5
n = 3

# create matrices
A   = np.random.randn(m,n)
AtA = np.matrix.transpose(A)@A
AAt = A@np.matrix.transpose(A)

# first, show that they are square
print( AtA.shape )
print( AAt.shape )


# next, show that they are symmetric
print( AtA - np.matrix.transpose(AtA) )
print( AAt - np.matrix.transpose(AAt) )

(3, 3)
(5, 5)
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
