#Generate a 2X2 matrix with integers that have linear dependences, compute det(A)
#Generate random nXn matrices with linear dependence.

A = a  b
    c  d
    
    For matrix A, determinant is calculated as ad-bc

In [2]:
import numpy as np

In [4]:
A = [[1,2],[1,2]]
np.linalg.det(A)

#determinant = ad-bc


0.0

In [5]:
import numpy as np
from numpy.random import randint

In [8]:
#Lets generate random matrix of size 5

M1 = randint(1,10,25).reshape(5,5)
print(M1)
np.linalg.det(M1)

[[6 8 8 2 2]
 [2 6 2 9 2]
 [6 9 9 2 3]
 [3 9 5 1 8]
 [6 8 3 6 8]]


-1084.0000000000002

In [12]:
M2 = randint(1,20,25).reshape(5,5)
print(M2)
np.linalg.det(M2)

[[ 9 17  4 12  8]
 [ 1 15 18  8 18]
 [11 12  9  6 19]
 [15 19 12 16  5]
 [15  6 17  4 11]]


-44032.000000000015

In [16]:
#Now let us try to generate an identity matrix and calculate the determinant

I = np.eye(3)
print(np.linalg.det(I))

I2 = np.eye(7)
np.linalg.det(I2)

#it is clear that determinant of an identity matrix will always be zero.

1.0


1.0

In [23]:
M3 = randint(1,100,100).reshape(10,10)

#make the matrix linear dependent
M3[:,1] = M3[:,2]
np.linalg.det(M3)

60.35707401520241